export const domains = [
  {
    type: "domain",
    title: "CAVERN",
    description: "Place of stone and darkness.",
    aliases: ["cr"],
    dangers: {
      33: "Denizen lairs here",
      36: "Cave-in",
      39: "Flooding",
      42: "Perilous climb or descent",
      45: "Fissure or sinkhole",
    },
    features: {
      43: "Twisting passages",
      56: "Cramped caves",
      64: "Vast chamber",
      68: "Subterranean waterway",
      72: "Cave pool",
      76: "Natural bridge",
      80: "Towering stone formations",
      84: "Natural illumination",
      88: "Dark pit",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "FROZENCAVE",
    description: "A place of deep caves and enduring edge.",
    aliases: ["cr"],
    dangers: {
      33: "Denizen lairs here",
      36: "Fracturing ice",
      39: "Crumbling chasm ",
      42: "Bitter chill",
      45: "Disorienting reflections",
    },
    features: {
      43: "Maze of icy tunnels",
      56: "Glistening cave",
      64: "Vast chamber",
      68: "Frigid waterway",
      72: "Icy pools",
      76: "Magnificent ice formations",
      80: "Frozen waterfall",
      84: "Deep crevasses",
      88: "Discovery locked in the ice",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "ICEREACH",
    description: "A frigid landscape formed of frozen seas.",
    aliases: ["cr"],
    dangers: {
      33: "Denizen hunts",
      36: "Fragile ice above watery depths",
      39: "Perilous climb or descent",
      42: "Avalanche or icefall",
      45: "Foul weather",
    },
    features: {
      43: "Plains of ice and snow",
      56: "Seawater channel",
      64: "Icy highlands",
      68: "Crevasse",
      72: "Ice floes",
      76: "Ship trapped in ice",
      80: "Animal herd or habitat",
      84: "Frozen carcass",
      88: "Camp or outpost",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "RUIN",
    description: "The crumbling legacy of a dead civilization.",
    aliases: ["cr"],
    dangers: {
      33: "Ancient mechanism or trap",
      36: "Collapsing wall or ceiling",
      39: "Blocked or broken passage",
      42: "Unstable floor above a new danger",
      45: "Ancient secrets best left buried",
    },
    features: {
      43: "Crumbling corridors and chambers",
      56: "Collapsed architecture",
      64: "Rubble-choked hall",
      68: "Courtyard",
      72: "Archive or library",
      76: "Broken statuary or fading murals",
      80: "Preserved vault",
      84: "Temple to forgotten gods",
      88: "Mausoleum",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "SHADOWFEN",
    description: "A primeval marsh, cloaked in mist.",
    aliases: ["cr"],
    dangers: {
      33: "Denizen hunts",
      36: "Deep water blocks the path",
      39: "Toxic environment",
      42: "Concealing or disorienting mist",
      45: "Hidden quagmire",
    },
    features: {
      43: "Narrow path through a fetid bog",
      56: "Stagnant waterway",
      64: "Flooded thicket",
      68: "Island of dry land",
      72: "Submerged discovery",
      76: "Preserved corpses",
      80: "Overgrown structure",
      84: "Tall reeds",
      88: "Camp or outpost",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },

  {
    type: "domain",
    title: "STRONGHOLD",
    description: "A fortress secured against trespassers.",
    aliases: ["cr"],
    dangers: {
      33: "Blocked or guarded path",
      36: "Caught in the open",
      39: "Chokepoint",
      42: "Trap",
      45: "Alarm trigger",
    },
    features: {
      43: "Connecting passageways",
      56: "Barracks or common quarters",
      64: "Large hall",
      68: "Workshop or library",
      72: "Command center or leadership",
      76: "Ladder or stairwell",
      80: "Storage",
      84: "Kitchen or larder",
      88: "Courtyard",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "UNDERKEEP",
    description: "An age-old subterranean dungeon.",
    aliases: ["cr"],
    dangers: {
      33: "Ancient mechanism or trap",
      36: "Crumbling architecture",
      39: "Blocked or broken passage",
      42: "Artifact with a hidden danger",
      45: "Denizen lurks in darkness",
    },
    features: {
      43: "Dense thicket",
      56: "Overgrown path",
      64: "Waterway",
      68: "Clearing",
      72: "Elder tree",
      76: "Brambles",
      80: "Overgrown structure",
      84: "Rocky outcrop",
      88: "Camp or outpost",
      98: "Something unusual or unexpected",
      99: "You transition into a new theme",
      100: "You transition into a new domain",
    },
  },
  {
    type: "domain",
    title: "PLACE",
    description: "for custom domain",
    aliases: ["cr"],
    dangers: {
      33: "domain danger",
      36: "domain danger",
      39: "domain danger",
      42: "domain danger",
      45: "domain danger",
    },
    features: {
      43: "domain feature",
      56: "domain feature",
      64: "domain feature",
      68: "domain feature",
      72: "domain feature",
      76: "domain feature",
      80: "domain feature",
      84: "domain feature",
      88: "domain feature",
      98: "domain feature",
      99: "You transition into a new theme. Send `.to-theme <theme name>`. To see all themes send `.to-theme` without parameter.",
      100: "You transition into a new domain. Send `.to-domain <domain name>`. To see all domains send `.to-domain` without parameter.",
    },
  },
];

export const themes = [
  {
    type: "theme",
    title: "ANCIENT",
    description: "This place holds the secrets of a bygone age",
    aliases: ["cr"],
    dangers: {
      5: "Ancient trap",
      10: "Hazardous architecture or terrain",
      12: "Blocked or broken path",
      14: "Denizen protects an ancient secret",
      16: "Denizen reveres an ancient power",
      18: "Living relics of a lost age",
      20: "Ancient evil resurgent",
      22: "Dire warnings of a long-buried danger",
      24: "Ancient disease or contamination",
      26: "Artifact of terrible meaning or power",
      28: "Disturbing evidence of ancient wrongs",
      30: "Others seek power or knowledge",
    },
    features: {
      4: "Evidence of lost knowledge",
      8: "Inscrutable relics",
      12: "Ancient artistry or craft",
      16: "Preserved corpses or fossils",
      20: "Visions of this place in another time",
    },
  },
  {
    type: "theme",
    title: "CORRUPTED",
    description: "This place is tainted by dark magic.",
    aliases: ["cr"],
    dangers: {
      5: "Denizen spawned from dark magic",
      10: "Denizen controls dark magic",
      12: "Denizen corrupted by dark magic",
      14: "Corruption marks you",
      16: "Innocents held in thrall1",
      18: "Revelations of a terrible truth",
      20: "Mystic trap or trigger",
      22: "Mystic barrier or ward",
      24: "Illusions lead you astray",
      26: "Dark ritual in progress",
      28: "Lingering effects of a dark ritual",
      30: "Dread harbingers of a greater magic",
    },
    features: {
      4: "Mystic focus or conduit",
      8: "Strange environmental disturbances",
      12: "Mystic runes or markings",
      16: "Blight or decay",
      20: "Evidence of a foul ritual",
    },
  },
  {
    type: "theme",
    title: "WILD",
    description: "Nature prevails in this place.",
    aliases: ["cr"],
    dangers: {
      5: "Denizen hunts",
      10: "Denizen strikes without warning",
      12: "Denizen leverages the environment ",
      14: "Denizen wields unexpected abilities",
      16: "Denizen guided by a greater threat",
      18: "Denizen protects something",
      20: "Hazardous terrain",
      22: "Weather or environmental threat",
      24: "Benign aspect becomes a threat",
      26: "Overzealous hunter",
      28: "Disturbing evidence of a victim’s fate",
      30: "Ill-fated victim in danger",
    },
    features: {
      4: "Denizen’s lair",
      8: "Territorial markings",
      12: "Impressive flora or fauna",
      16: "Hunting ground or watering hole",
      20: "Remains or carrion",
    },
  },
  {
    type: "theme",
    title: "HAUNTED",
    description: "Restless spirits are bound to this place.",
    aliases: ["cr"],
    dangers: {
      5: "Denizen haunts this area",
      10: "Unsettling sounds or foreboding signs",
      12: "Denizen attacks without warning",
      14: "Denizen makes a costly demand",
      16: "Denizen seizes your body or mind",
      18: "Denizen taunts or lures you",
      20: "A disturbing truth is revealed",
      22: "Frightening visions",
      24: "The environment is used against you",
      26: "Trickery leads you astray",
      28: "True nature of this place is revealed ",
      30: "Sudden, shocking manifestation",
    },
    features: {
      4: "Tomb or burial site",
      8: "Blood was spilled here",
      12: "Unnatural mists or darkness ",
      16: "Messages from beyond the grave",
      20: "Apparitions of a person or event",
    },
  },
  {
    type: "theme",
    title: "CUSTOM",
    description: "for custom theme",
    aliases: ["cr"],
    dangers: {
      5: "theme danger",
      10: "theme danger",
      12: "theme danger",
      14: "theme danger",
      16: "theme danger",
      18: "theme danger",
      20: "theme danger",
      22: "theme danger",
      24: "theme danger",
      26: "theme danger",
      28: "theme danger",
      30: "theme danger",
    },
    features: {
      4: "theme domain",
      8: "theme domain",
      12: "theme domain",
      16: "theme domain",
      20: "theme domain",
    },
  },
];

export const deepInDelvePoints = {
  progressAndDanger: {
    k: "progressAndDanger",
    value: "Progress noted. You have advanced, but you are in danger!\n",
  },
  progress: { k: "progress", value: "You have advanced. Mark progress." },
  progressOrOpportunity: {
    k: "progressOrOpportunity",
    value:
      "Choose one: mark progress or *Find opportunity* (send `.opportunity`).",
  },
  progressAndOpportunity: {
    k: "progressAndOpportunity",
    value: "Progress noted. You discover an opportunity (send `.opportunity`).",
  },
  doubleProgress: {
    k: "doubleProgress",
    value:
      "Progress marked twice! You've made good progress, but you're in danger!\n",
  },
};

export const deepInDelveTables = {
  edge: {
    title: "edge",
    results: {
      45: deepInDelvePoints.progressAndDanger,
      65: deepInDelvePoints.progress,
      75: deepInDelvePoints.progressOrOpportunity,
      80: deepInDelvePoints.progressAndOpportunity,
      100: deepInDelvePoints.doubleProgress,
    },
  },
  shadow: {
    title: "shadow",
    results: {
      30: deepInDelvePoints.progressAndDanger,
      65: deepInDelvePoints.progress,
      90: deepInDelvePoints.progressOrOpportunity,
      99: deepInDelvePoints.progressAndOpportunity,
      100: deepInDelvePoints.doubleProgress,
    },
  },
  wits: {
    title: "wits",
    results: {
      40: deepInDelvePoints.progressAndDanger,
      55: deepInDelvePoints.progress,
      80: deepInDelvePoints.progressOrOpportunity,
      99: deepInDelvePoints.progressAndOpportunity,
      100: deepInDelvePoints.doubleProgress,
    },
  },
};

export const findOportunityTable = {
  25: "The terrain favors you, or you will find a hidden path.",
  45: "An aspect of the history or nature of this place is revealed.",
  57: "You find a safe area.",
  68: "Hint offers insight or direction.",
  78: "You catch the dweller by surprise.",
  86: "This area provides the ability to loot, forage, or hunt.",
  90: "You find an interesting or useful item.",
  94: "You've been warned of a momentum threat.",
  98: "You meet an denizen who can help you.",
  100: "You have encountered an denizen in need of help.",
};

export const revealDangerTable = {
  57: "You are facing a hostile occupant.",
  68: "You are facing a natural or architectural hazard.",
  76: "You discover something that undermines or complicates your quest.",
  79: "You are facing a heartbreaking situation or feeling.",
  82: "You are facing the consequences of an earlier choice or approach.",
  85: "Your path is blocked or trapped.",
  88: "Resource has been reduced, broken, or lost.",
  91: "You are faced with an enigmatic riddle or a difficult choice.",
  94: "You have lost your way or are delayed.",
  100: "Throw twice. Both results",
};
